export const myGraphData = {
    nodes: [
        { id: 'Ana', group: 'Influencer', avatar: 'woman.png' },
        { id: 'Bruno', group: 'Friend', avatar: 'man.png' },
        { id: 'Carla', group: 'Family', avatar: 'woman.png' },
        { id: 'Diego', group: 'Follower', avatar: 'man.png' },
        { id: 'Eduarda', group: 'Follower', avatar: 'woman.png' },
        { id: 'Felipe', group: 'Friend', avatar: 'man.png' },
        { id: 'Alice', group: 'Friend', avatar: 'woman.png' },
        { id: 'Pedro', group: 'Family', avatar: 'man.png' },
        { id: 'Henrique', group: 'Friend', avatar: 'man.png' },
        { id: 'Eva', group: 'Friend', avatar: 'woman.png' },
        { id: 'João', group: 'Friend', avatar: 'man.png' },
        { id: 'Lucas', group: 'Follower', avatar: 'man.png' },
        { id: 'Miguel', group: 'Follower', avatar: 'man.png' },
        { id: 'Rafael', group: 'Follower', avatar: 'man.png' },
        { id: 'Vitor', group: 'Follower', avatar: 'man.png' },
        { id: 'Beatriz', group: 'Follower', avatar: 'woman.png' },
        { id: 'Juliana', group: 'Follower', avatar: 'woman.png' },
        { id: 'Patricia', group: 'Follower', avatar: 'woman.png' },
        { id: 'Sofia', group: 'Follower', avatar: 'woman.png' },
    ],
    // friend weight = 0.6
    // family weight = 0.3
    // follower weight = 0.9
    links: [
        { source: 'Ana', target: 'Bruno', type: 'Follower' },
        { source: 'Pedro', target: 'Carla', type: 'Family' },
        { source: 'Carla', target: 'Pedro', type: 'Family' },
        { source: 'Bruno', target: 'Carla', type: 'Friend' },
        { source: 'Carla', target: 'Bruno', type: 'Friend' },
        { source: 'Ana', target: 'Carla', type: 'Follower' },
        { source: 'Ana', target: 'Diego', type: 'Follower' },
        { source: 'Ana', target: 'Eva', type: 'Follower' },
        { source: 'Ana', target: 'Pedro', type: 'Follower' },
        { source: 'Bruno', target: 'Eduarda', type: 'Friend' },
        { source: 'Eduarda', target: 'Bruno', type: 'Friend' },
        { source: 'Eduarda', target: 'João', type: 'Friend' },
        { source: 'Carla', target: 'Eva', type: 'Friend' },
        { source: 'Eva', target: 'Carla', type: 'Friend' },
        { source: 'Carla', target: 'Felipe', type: 'Friend' },
        { source: 'Felipe', target: 'Henrique', type: 'Friend' },
        { source: 'Ana', target: 'Felipe', type: 'Follower' },
        { source: 'Alice', target: 'Henrique', type: 'Friend' },
        { source: 'Henrique', target: 'Alice', type: 'Friend' },
        // Exemplos de links para os novos nós
        { source: 'Ana', target: 'Lucas', type: 'Follower' },
        { source: 'Ana', target: 'Miguel', type: 'Follower' },
        { source: 'Ana', target: 'Rafael', type: 'Follower' },
        { source: 'Ana', target: 'Vitor', type: 'Follower' },
        { source: 'Ana', target: 'Beatriz', type: 'Follower' },
        { source: 'Ana', target: 'Juliana', type: 'Follower' },
        { source: 'Ana', target: 'Patricia', type: 'Follower' },
        { source: 'Ana', target: 'Sofia', type: 'Follower' },
        { source: 'Alice', target: 'Lucas', type: 'Friend' },
        { source: 'João', target: 'Lucas', type: 'Friend' },
        { source: 'Sofia', target: 'Lucas', type: 'Friend' },
        { source: 'Vitor', target: 'Eduarda', type: 'Friend' },
        { source: 'Eduarda', target: 'Vitor', type: 'Friend' },
    ]
};